"""Pydantic schemas for the application."""
from app.schemas.benchmark import BenchmarkDataset, BenchmarkTask, DatasetSummary
from app.schemas.evaluation import (
    BenchmarkEvaluationResult,
    BenchmarkSummary,
    CompareBenchmarksRequest,
    EvaluationComparisonResult,
    EvaluationMetric,
    EvaluationProfile,
    EvaluationWeightConfig,
    ExecutionStatistics,
    FailureAnalysis,
    FailureDetail,
    FailureType,
    MetricBreakdown,
    MetricName,
    TaskEvaluationResult,
)
from app.schemas.execution import (
    AgentDecision,
    AgentExecutionResult,
    AgentModelConfig,
    AgentTaskPayload,
    BenchmarkTaskExecutionRequest,
    CustomTaskExecutionRequest,
    ExecutionTraceResponse,
    ExecutionTraceStep,
)
from app.schemas.llm import (
    ModelInferenceRequest,
    ModelInferenceResponse,
    ModelMetadata,
    TokenUsage,
)
from app.schemas.tool import (
    CalculatorInput,
    CalculatorOutput,
    FakeWebSearchInput,
    FakeWebSearchOutput,
    FakeWebSearchResult,
    ToolExecutionRequest,
    ToolExecutionResponse,
    ToolMetadata,
    UnitConverterInput,
    UnitConverterOutput,
)

__all__ = [
    "BenchmarkDataset",
    "BenchmarkTask",
    "BenchmarkEvaluationResult",
    "BenchmarkSummary",
    "CalculatorInput",
    "CalculatorOutput",
    "CompareBenchmarksRequest",
    "DatasetSummary",
    "AgentDecision",
    "AgentExecutionResult",
    "AgentModelConfig",
    "AgentTaskPayload",
    "BenchmarkTaskExecutionRequest",
    "CustomTaskExecutionRequest",
    "EvaluationComparisonResult",
    "EvaluationMetric",
    "EvaluationProfile",
    "EvaluationWeightConfig",
    "ExecutionStatistics",
    "ExecutionTraceResponse",
    "ExecutionTraceStep",
    "FailureAnalysis",
    "FailureDetail",
    "FailureType",
    "FakeWebSearchInput",
    "FakeWebSearchOutput",
    "FakeWebSearchResult",
    "MetricBreakdown",
    "MetricName",
    "ModelInferenceRequest",
    "ModelInferenceResponse",
    "ModelMetadata",
    "TaskEvaluationResult",
    "ToolExecutionRequest",
    "ToolExecutionResponse",
    "ToolMetadata",
    "TokenUsage",
    "UnitConverterInput",
    "UnitConverterOutput",
]
